### ISSUE TITLE
Loading screens very slow, I assume because of addressables

### ISSUE THREAD

**Issue by whynames** [Haruma-K/UnityScreenNavigator#34]
Loading screens very slow, I assume because of addressables. What are the recommended settings? Is it how it is supposed to be? Can we switch it to resources for simple use cases easily?

**Comment by Haruma-K** [comment]
I don't believe the slow loading issue is due to this library. There can be various reasons, so it's hard to pinpoint exactly. If you're concerned about the library's performance, I suggest trying it out with simpler resources.

> Can we switch it to resources for simple use cases easily?

You can use ResourcesAssetLoader instead of AddressableAssetLoader.

https://github.com/Haruma-K/UnityScreenNavigator/blob/master/Assets/UnityScreenNavigator/Runtime/Foundation/AssetLoader/ResourcesAssetLoader.cs
